name: "AI Repo Recommender Action"
description: "Analyze code changes and provide comments as asked by user using the OpenAI API."
inputs:
  # GitHub-related parameters
  GIITHUB_TOKEN:
    description: "Token for interacting with the GitHub API."
    required: true

  # OpenAI-related parameters
  OPENAI_API_KEY:
    description: "A key to authenticate requests to the OpenAI API."
    required: true
  OPENAI_API_MODEL:
    description: "Model to use when calling the OpenAI API."
    required: false
    default: "gpt-4"
  REPO_RECOMMENDER_ACTION:
    description: "Action to be performed like prreview"
    required: true

  # Optional settings
  FILE_EXCLUDE_PATTERNS:
    description: "Glob patterns to exclude files from the diff analysis."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: "actions/setup-python@v5"
      with:
        python-version: "3.11"

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "Run the Python script"
      run: python src/main.py

branding:
  icon: "aperture"
  color: "green"
